// This entry assembles balanced modules generated from the CRT effect.
// Files are ordered by dependency and each remains below 300 lines.
#include "crt-modules/module-010.fxh"
#include "crt-modules/module-011.fxh"
#include "crt-modules/module-012.fxh"
#include "crt-modules/module-013.fxh"
#include "crt-modules/module-014.fxh"
#include "crt-modules/module-015.fxh"
#include "crt-modules/module-016.fxh"
#include "crt-modules/module-017.fxh"
#include "crt-modules/module-018.fxh"
#include "crt-modules/module-019.fxh"
#include "crt-modules/module-020.fxh"
#include "crt-modules/module-021.fxh"
#include "crt-modules/module-022.fxh"
#include "crt-modules/module-023.fxh"
#include "crt-modules/module-024.fxh"
#include "crt-modules/module-025.fxh"
#include "crt-modules/module-026.fxh"
#include "crt-modules/module-027.fxh"
#include "crt-modules/module-028.fxh"
#include "crt-modules/module-029.fxh"
#include "crt-modules/module-030.fxh"
#include "crt-modules/module-031.fxh"
#include "crt-modules/module-032.fxh"
